Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Controllers/FdistributionController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zero_Hunger.Models;

namespace Zero_Hunger.Controllers
{
    public class FdistributionController : Controller
    {
        ZhungerEntities db = new ZhungerEntities();
        // GET: Fdistribution
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Save(Fdistribution fd)
        {
           //if(ModelState.IsValid)
            //{
                db.Fdistributions.Add(fd);
                var res = db.Frestaurents.SingleOrDefault(e => e.resname == fd.resname);
                if (res == null)
                    return HttpNotFound("Restaurent not found");
                res.available = "yes";
                db.Entry(res).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            //}
           //return View(fd);
        }



        [HttpPost]
        public ActionResult Getid(String resname)
        {
           var rest = (from s in db.ngoes where s.resid == resname
                       select new
                       {
                           StartDate =s.sdate,
                           EndDate =s.edate,
                           Employeeid = s.employeeid,
                           Resname = s.resid,
                           Exdate = SqlFunctions.DateDiff("day",s.edate,DateTime.Now)
                       }).ToArray();


            return Json(rest,JsonRequestBehavior.AllowGet);

        }

    }
}

Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Controllers/FrestaurentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zero_Hunger.Models;

namespace Zero_Hunger.Controllers
{
    public class FrestaurentsController : Controller
    {
        private ZhungerEntities db = new ZhungerEntities();

        // GET: Frestaurents
        public ActionResult Index()
        {
            return View(db.Frestaurents.ToList());
        }
       

        // GET: Frestaurents/Details/5
        public ActionResult Details(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frestaurent frestaurent = db.Frestaurents.Find(id);
            if (frestaurent == null)
            {
                return HttpNotFound();
            }
            return View(frestaurent);
        }

        // GET: Frestaurents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Frestaurents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,resname,address,fooditem,available,date")] Frestaurent frestaurent)
        {
            if (ModelState.IsValid)
            {
                db.Frestaurents.Add(frestaurent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(frestaurent);
        }

        // GET: Frestaurents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frestaurent frestaurent = db.Frestaurents.Find(id);
            if (frestaurent == null)
            {
                return HttpNotFound();
            }
            return View(frestaurent);
        }

        // POST: Frestaurents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,resname,address,fooditem,available,date")] Frestaurent frestaurent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(frestaurent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(frestaurent);
        }

        // GET: Frestaurents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Frestaurent frestaurent = db.Frestaurents.Find(id);
            if (frestaurent == null)
            {
                return HttpNotFound();
            }
            return View(frestaurent);
        }

        // POST: Frestaurents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Frestaurent frestaurent = db.Frestaurents.Find(id);
            db.Frestaurents.Remove(frestaurent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zero Hunger BD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Employee", "Login", "employeelogin")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                   



                </ul>
                <ul class="nav navbar-nav" style="float:right !important">
                    @if (Session["username"] != null)
                    {
                        <li>@Html.ActionLink("Admin Collect", "Index", "Fdistribution")</li>
                        <li>@Html.ActionLink("Share Food❤", "Create", "Frestaurents")</li>
                        <li><p style="color:#0094ff; margin-top:15px;"> Hello @Session["username"] </p></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Restaurent")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("SignUp", "SignUp", "Restaurent")</li>
                        <li>@Html.ActionLink("Login", "Login", "Restaurent")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>