Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Models/ngo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngo
    {
        public int id { get; set; }
        public string resid { get; set; }
        public int employeeid { get; set; }
        public System.DateTime sdate { get; set; }
        public System.DateTime edate { get; set; }
    }
}

Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Controllers/ngoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Zero_Hunger.Models;

namespace Zero_Hunger.Controllers
{
    public class ngoController : Controller
    {

        ZhungerEntities db = new ZhungerEntities();

        // GET: ngo
        public ActionResult Index()
        {
            var result = (from r in db.ngoes
                          join c in db.Frestaurents on r.resid equals c.resname

                          select new NgoAvail
                          {
                            id = r.id,
                            resid = r.resid,
                            employeeid = r.employeeid,
                            sdate = r.sdate,
                            edate = r.edate,
                            available = c.available


                          }).ToList();




            return View(result);
        }

        [HttpGet]
        public ActionResult Getres()
        {
           var res = db.Frestaurents.ToList();
            return Json(res, JsonRequestBehavior.AllowGet);


        }


        [HttpPost]
        public ActionResult Getid(int id)
        {
            var emp = (from s in db.employees where s.id == id select s.employeename).ToList();
            return Json(emp, JsonRequestBehavior.AllowGet);


        }


        [HttpPost]
        public ActionResult Getavail(String resname)
        {
           var foodavail = (from s in db.Frestaurents where s.resname == resname select s.available).FirstOrDefault();
            return Json(foodavail, JsonRequestBehavior.AllowGet);


        }









        [HttpPost]
        public ActionResult Save(ngo NGO)
        {
            
           if(ModelState.IsValid)
            {
                db.ngoes.Add(NGO);
                var Res = db.Frestaurents.SingleOrDefault(e => e.resname == NGO.resid);
                if (Res == null)
                    return HttpNotFound("Restaurant is not available");
                Res.available = "no";
                db.Entry(Res).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

               
            }
           return View(NGO);

        }




    }
}

Zero Hunger(Full)/Zero_Hunger/Zero_Hunger/Views/ngo/Index.cshtml
@model IEnumerable<Zero_Hunger.Models.NgoAvail>


<div class="row">

    <div class="col-sm-3">




        @using (Html.BeginForm("Save", "ngo", FormMethod.Post, new { id = "popupForm" }))
        {

            <div>

                <h1> Zero Hunger NGO Bangladesh </h1>
            </div>

            <div class="form-group">
                <label class="form-label"> Restaurent Name</label>
                <select class="form-control" id="resid" name="resid" placeholder="Restaurent Name" required>
                    <option> Please select </option>
                </select>
            </div>

            <div class="form-group">
                <label class="form-label"> Employee Id</label>
                <input type="text" id="employeeid" name="employeeid" class="form-control" placeholder="Employee ID" required>

            </div>

            <div class="form-group">
                <label class="form-label"> Employee Name</label>
                <input type="text" id="employeename" name="employeename" class="form-control" placeholder="Employee Name" required>

            </div>


            <div class="form-group">
                <label class="form-label"> Start Date</label>
                <input type="date" id="sdate" name="sdate" class="form-control" placeholder="Start Date" required>

            </div>

            <div class="form-group">
                <label class="form-label"> End Date</label>
                <input type="date" id="edate" name="edate" class="form-control" placeholder="Start Date" required>

            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />

            </div>

        }

    </div>

    <div class="col-sm-8">


<table class="table">

    <tr>
        <th>Restaurent Name</th>
        <th>Employee ID</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Availablity</th>

    </tr>

    @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @item.resid
                    </td>
                    <td>
                        @item.employeeid
                    </td>
                    <td>
                        @item.sdate
                    </td>
                    <td>
                        @item.edate
                    </td>
                    <td>
                        @item.available
                    </td>
                </tr>
            }

</table>




    </div>

    </div>

    @section scripts
{
        <script src="~/Scripts/jquery-3.4.1.js"></script>
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>

        <script>
            getRes();
            load();

            function load() {

                $("#employeeid").attr("disabled", "disabled");
                $("#employeename").attr("disabled", "disabled");
                $("#sdate").attr("disabled", "disabled");
                $("#edate").attr("disabled", "disabled");

            }








            function getRes() {

                $.ajax({

                    type: 'GET',
                    url: '/ngo/Getres',
                    dataType: 'JSON',
                    success: function (data) {

                        console.log(data);

                        for (var i = 0; i < data.length; i++) {


                            $("#resid").append($("<option/>", {
                                text: data[i].resname
                            }));


                        }





                    }





                });



            }

            $("#resid").change(function () {


                available();

            });

            function available() {

                $.ajax({

                    type: 'POST',
                    url: '/ngo/Getavail?resname=' + $("#resid").val(),
                    dataType: 'JSON',
                    success: function (data) {

                        console.log(data)

                        var avl = data;

                        if (avl == "yes") {

                            $("#employeeid").removeAttr('disabled');
                            $("#employeename").removeAttr('disabled');
                            $("#sdate").removeAttr('disabled');
                            $("#edate").removeAttr('disabled');

                        }
                        else {

                            $("#employeeid").attr("disabled", "disabled");
                            $("#employeename").attr("disabled", "disabled");
                            $("#sdate").attr("disabled", "disabled");
                            $("#edate").attr("disabled", "disabled");
                        }




                    }

                });


            }









            getEmp();

            function getEmp() {

                $("#employeeid").keyup(function (e) {


                    $.ajax({

                        type: 'POST',
                        url: '/ngo/Getid?id=' + $("#employeeid").val(),
                        dataType: 'JSON',
                        success: function (data) {

                            console.log(data)

                            $("#employeename").val(data)



                        }

                    });


                });
            }




        </script>










    }